DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(30) DEFAULT NULL,
  last_name VARCHAR(30) DEFAULT NULL,
  email VARCHAR(30) DEFAULT NULL,
  phone VARCHAR(30) DEFAULT NULL,
  username VARCHAR(30) DEFAULT NULL,
  password VARCHAR(30) DEFAULT NULL,
  birth VARCHAR(30) DEFAULT NULL,
  gender INT DEFAULT NULL
);